#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jellyfish
Version  : 0.9.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/26/18/cd485f3661c8e8c0ab864c2e54033371dcc1f7e75767318a4044b2808ed4/jellyfish-0.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/26/18/cd485f3661c8e8c0ab864c2e54033371dcc1f7e75767318a4044b2808ed4/jellyfish-0.9.0.tar.gz
Summary  : a library for doing approximate and phonetic matching of strings.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-jellyfish-filemap = %{version}-%{release}
Requires: pypi-jellyfish-lib = %{version}-%{release}
Requires: pypi-jellyfish-license = %{version}-%{release}
Requires: pypi-jellyfish-python = %{version}-%{release}
Requires: pypi-jellyfish-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Overview
**jellyfish** is a library for approximate & phonetic matching of strings.

%package filemap
Summary: filemap components for the pypi-jellyfish package.
Group: Default

%description filemap
filemap components for the pypi-jellyfish package.


%package lib
Summary: lib components for the pypi-jellyfish package.
Group: Libraries
Requires: pypi-jellyfish-license = %{version}-%{release}
Requires: pypi-jellyfish-filemap = %{version}-%{release}

%description lib
lib components for the pypi-jellyfish package.


%package license
Summary: license components for the pypi-jellyfish package.
Group: Default

%description license
license components for the pypi-jellyfish package.


%package python
Summary: python components for the pypi-jellyfish package.
Group: Default
Requires: pypi-jellyfish-python3 = %{version}-%{release}

%description python
python components for the pypi-jellyfish package.


%package python3
Summary: python3 components for the pypi-jellyfish package.
Group: Default
Requires: pypi-jellyfish-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(jellyfish)

%description python3
python3 components for the pypi-jellyfish package.


%prep
%setup -q -n jellyfish-0.9.0
cd %{_builddir}/jellyfish-0.9.0
pushd ..
cp -a jellyfish-0.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653338624
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jellyfish
cp %{_builddir}/jellyfish-0.9.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jellyfish/ab0b6e216612db7b4869aa563d99a19a2a19d75e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-jellyfish

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jellyfish/ab0b6e216612db7b4869aa563d99a19a2a19d75e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
